#!/usr/bin/python

import os, sys

try:
    WL_HOME = "###MW_HOME###/wlserver"
    DOMAIN_HOME = "###DOMAIN_HOME###"
    ORACLE_HOME = "###MW_HOME###/idm"
    if DOMAIN_HOME is None:
        sys.exit("Error: Please set the environment variable DOMAIN_HOME")
    if WL_HOME is None:
        sys.exit("Error: Please set the environment variable WL_HOME")
    if ORACLE_HOME is None:
        sys.exit("Error: Please set the environment variable ORACLE_HOME")
except (KeyError), why:
    sys.exit("Error: Missing Environment Variables " + str(why))
readDomain(r'###DOMAIN_HOME###')
selectTemplate('Oracle Identity Manager')
loadTemplates()
showTemplates()
if isJMSStorePersistenceConfigurable() and not isJMSStoreDBPersistenceSet():(enableJMSStoreDBPersistence(true))
cd('/Server/oim_server1')
cmo.setListenPort(14000)
create('oim_server1','SSL')
cd('SSL/oim_server1')
cmo.setEnabled(true)
cmo.setListenPort(14001)
cd('/')
cd('/Server/oim_server1')
cmo.setListenAddress('###ADMIN_HOST###')
cd('/')
cd('Credential/TargetStore/oim')
cd('TargetKey/keystore')
create('c','Credential')
cd('Credential')
set('Username','keystore')
set('Password','###KEYSTORE_PASSWORD###')
cd('/')
cd('Credential/TargetStore/oim')
cd('TargetKey/OIMSchemaPassword')
create('c','Credential')
cd('Credential')
set('Username','###RCUPREFIX###_OIM')
set('Password','###DB_SCHEMA_PASSWORD###')
cd('/')
cd('Credential/TargetStore/oim')
cd('TargetKey/sysadmin')
create('c','Credential')
cd('Credential')
set('Username','xelsysadm')
set('Password','###ADMIN_PASSWORD###')
cd('/')
cd('Credential/TargetStore/oim')
cd('TargetKey/WeblogicAdminKey')
create('c','Credential')
cd('Credential')
set('Username','###ADMIN_USER###')
set('Password','###ADMIN_PASSWORD###')
cd('/JdbcSystemResource/soaOIMLookupDB/JdbcResource/soaOIMLookupDB/JdbcDriverParams/NO_NAME')
cmo.setUrl('jdbc:oracle:thin:@###CONNECTION_STR###')
cmo.setDriverName('oracle.jdbc.xa.client.OracleXADataSource')
set('PasswordEncrypted', '###DB_SCHEMA_PASSWORD###')
cd('Properties/NO_NAME/Property/user')
cmo.setValue('###RCUPREFIX###_OIM')
cd('/JdbcSystemResource/oimJMSStoreDS/JdbcResource/oimJMSStoreDS/JdbcDriverParams/NO_NAME')
cmo.setUrl('jdbc:oracle:thin:@###CONNECTION_STR###')
cmo.setDriverName('oracle.jdbc.OracleDriver')
set('PasswordEncrypted', '###DB_SCHEMA_PASSWORD###')
cd('Properties/NO_NAME/Property/user')
cmo.setValue('###RCUPREFIX###_OIM')
cd('/JdbcSystemResource/ApplicationDB/JdbcResource/ApplicationDB/JdbcDriverParams/NO_NAME')
cmo.setUrl('jdbc:oracle:thin:@###CONNECTION_STR###')
cmo.setDriverName('oracle.jdbc.OracleDriver')
set('PasswordEncrypted', '###DB_SCHEMA_PASSWORD###')
cd('Properties/NO_NAME/Property/user')
cmo.setValue('###RCUPREFIX###_OIM')
cd('/JdbcSystemResource/WLSSchemaDataSource/JdbcResource/WLSSchemaDataSource/JdbcDriverParams/NO_NAME')
cmo.setUrl('jdbc:oracle:thin:@###CONNECTION_STR###')
cmo.setDriverName('oracle.jdbc.OracleDriver')
set('PasswordEncrypted', '###DB_SCHEMA_PASSWORD###')
cd('Properties/NO_NAME/Property/user')
cmo.setValue('###RCUPREFIX###_WLS')
cd('/JdbcSystemResource/mds-oim/JdbcResource/mds-oim/JdbcDriverParams/NO_NAME')
cmo.setUrl('jdbc:oracle:thin:@###CONNECTION_STR###')
cmo.setDriverName('oracle.jdbc.OracleDriver')
set('PasswordEncrypted', '###DB_SCHEMA_PASSWORD###')
cd('Properties/NO_NAME/Property/user')
cmo.setValue('###RCUPREFIX###_MDS')
cd('/JdbcSystemResource/oimOperationsDB/JdbcResource/oimOperationsDB/JdbcDriverParams/NO_NAME')
cmo.setUrl('jdbc:oracle:thin:@###CONNECTION_STR###')
cmo.setDriverName('oracle.jdbc.xa.client.OracleXADataSource')
set('PasswordEncrypted', '###DB_SCHEMA_PASSWORD###')
cd('Properties/NO_NAME/Property/user')
cmo.setValue('###RCUPREFIX###_OIM')
cd('/JdbcSystemResource/opss-data-source/JdbcResource/opss-data-source/JdbcDriverParams/NO_NAME')
cmo.setUrl('jdbc:oracle:thin:@###CONNECTION_STR###')
cmo.setDriverName('oracle.jdbc.OracleDriver')
set('PasswordEncrypted', '###DB_SCHEMA_PASSWORD###')
cd('Properties/NO_NAME/Property/user')
cmo.setValue('###RCUPREFIX###_OPSS')
cd('/JdbcSystemResource/opss-audit-DBDS/JdbcResource/opss-audit-DBDS/JdbcDriverParams/NO_NAME')
cmo.setUrl('jdbc:oracle:thin:@###CONNECTION_STR###')
cmo.setDriverName('oracle.jdbc.OracleDriver')
set('PasswordEncrypted', '###DB_SCHEMA_PASSWORD###')
cd('Properties/NO_NAME/Property/user')
cmo.setValue('###RCUPREFIX###_IAU_APPEND')
cd('/JdbcSystemResource/opss-audit-viewDS/JdbcResource/opss-audit-viewDS/JdbcDriverParams/NO_NAME')
cmo.setUrl('jdbc:oracle:thin:@###CONNECTION_STR###')
cmo.setDriverName('oracle.jdbc.OracleDriver')
set('PasswordEncrypted', '###DB_SCHEMA_PASSWORD###')
cd('Properties/NO_NAME/Property/user')
cmo.setValue('###RCUPREFIX###_IAU_VIEWER')
cd('/JdbcSystemResource/LocalSvcTblDataSource/JdbcResource/LocalSvcTblDataSource/JdbcDriverParams/NO_NAME')
cmo.setUrl('jdbc:oracle:thin:@###CONNECTION_STR###')
cmo.setDriverName('oracle.jdbc.OracleDriver')
set('PasswordEncrypted', '###DB_SCHEMA_PASSWORD###')
cd('Properties/NO_NAME/Property/user')
cmo.setValue('###RCUPREFIX###_STB')
updateDomain()
closeDomain()
exit()
